name: Build and Push Maven+Buildah Image

on:
  push:
    branches-ignore:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Parse versions from branch name
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

          if [[ "${GITHUB_REF##*/}" =~ ^jdk([0-9]+)-maven([0-9.]+)$ ]]; then
            JAVA_VERSION="${BASH_REMATCH[1]}"
            MAVEN_VERSION="${BASH_REMATCH[2]}"
          else
            echo "Branch name must match the pattern jdk<version>-maven<version>, e.g., jdk11-maven363"
            exit 1
          fi

          echo "JAVA_VERSION=$JAVA_VERSION" >> $GITHUB_ENV
          echo "MAVEN_VERSION=$MAVEN_VERSION" >> $GITHUB_ENV

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push Docker image
        run: |
          IMAGE_NAME="docker.io/${{ secrets.DOCKERHUB_USERNAME }}/maven-buildah:jdk${JAVA_VERSION}-maven${MAVEN_VERSION}"
          echo "Building image: $IMAGE_NAME"
          docker build \
            --build-arg JAVA_VERSION=${JAVA_VERSION} \
            --build-arg MAVEN_VERSION=${MAVEN_VERSION} \
            -t "$IMAGE_NAME" .
          docker push "$IMAGE_NAME"
