name: Build and Push Maven+Buildah Image

on:
  push:
    branches-ignore:
      - main

env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_REPO: your-dockerhub-username/maven-buildah

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set versions based on branch
        id: set_versions
        run: |
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          case "${GITHUB_REF##*/}" in
            "jdk11-maven363")
              echo "JAVA_VERSION=11.0.2+9" >> $GITHUB_ENV
              echo "MAVEN_VERSION=3.6.3" >> $GITHUB_ENV
              ;;
            "jdk11-maven362")
              echo "JAVA_VERSION=11.0.2+9" >> $GITHUB_ENV
              echo "MAVEN_VERSION=3.6.2" >> $GITHUB_ENV
              ;;
            *)
              # Default verziók
              echo "JAVA_VERSION=11.0.2+9" >> $GITHUB_ENV
              echo "MAVEN_VERSION=3.6.3" >> $GITHUB_ENV
              ;;
          esac

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPO }}:${{ env.BRANCH }}-${{ env.JAVA_VERSION }}-maven${{ env.MAVEN_VERSION }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE_REPO }}:latest
          build-args: |
            JAVA_VERSION=${{ env.JAVA_VERSION }}
            MAVEN_VERSION=${{ env.MAVEN_VERSION }}
